version: "3"
services:
  base:
    image: lawnmower-control:base
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    command: ros2 launch fwsbot fwsbot.launch.py
    # Networking
    network_mode: "host"
    ipc: host

  foxglove-websocket:
    image:  lawnmower-control:base
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml
    # Networking
    network_mode: "host"
    ipc: host

  foxglove-server:
    image: ghcr.io/foxglove/studio:latest
    ports:
      - "8080:8080"
    network_mode: "host"
    ipc: host
  
  # camera-stream:
  #   image: dustynv/ros:humble-ros-core-l4t-r32.7.1
  #   command: ros2 launch ros_deep_learning video_source.ros2.launch input:=csi://0
  #   # Networking
  #   network_mode: "host"
  #   ipc: host