version: "3"
services:
  base:
    image: lawnmower-control:base
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    command: ros2 launch fwsbot fwsbot.launch.py
    # Networking
    network_mode: "host"
    ipc: host

  foxglove-websocket:
    image:  lawnmower-control:base
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml
    # Networking
    network_mode: "host"
    ipc: host

  foxglove-server:
    image: ghcr.io/foxglove/studio:latest
    ports:
      - "8080:8080"
    network_mode: "host"
    ipc: host